Pathfinder_Class_Dict =	{
  0: "Alchemist",
  1: "Arcanist",
  2: "Barbarian",
  3: "Bard",
  4: "Bloodrager",
  5: "Cavalier",
  6: "Cleric",
  7: "Druid",
  8: "Fighter",
  9: "Hunter",
  10:"Inquisitor", 
  11:"Kineticist",
  12:"Magus",
  13:"Monk",
  14:"Oracle",
  15:"Paladin",
  16:"Ranger",
  17:"Rogue",
  18:"Shaman",
  19:"Skald",
  20:"Slayer",
  21:"Sorcerer",
  22:"Warpriest",
  23:"Witch",
  24:"Wizard",
  25:"Shifter",
}